name: Code Review con ChatGPT

on:
  pull_request:
    paths:
      - '**/*.html'
      - '**/*.js'
      - '**/*.py'

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install openai

    - name: Find changed files
      id: changes
      run: |
        echo "files=$(git diff --name-only origin/main...HEAD | grep -E '\.html$|\.js$|\.py$' | tr '\n' ' ')" >> "$GITHUB_OUTPUT"

    - name: Run ChatGPT review
      if: steps.changes.outputs.files != ''
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "Changed files: ${{ steps.changes.outputs.files }}"
        python3 scripts/chatgpt_review.py ${{ steps.changes.outputs.files }}

